import Head from "next/head";
import BaseLayout from "@/layouts/baseLayout";
import AppContainer from "@/components/atoms/appContainer";
import {
  GetServerSideProps,
  GetServerSidePropsContext,
  InferGetServerSidePropsType,
  PreviewData,
} from "next";
import { IMenu, IMenus } from "@/lib/entities/menu";
import fetchCommonData from "@/lib/usecases/fetchCommonData";
import { ParsedUrlQuery } from "querystring";
import getMenuByName from "@/lib/usecases/getMenu";
import BlocksRenderer from "@/components/molecules/blocksRenderer";

export const getServerSideProps = (async (
  context: GetServerSidePropsContext<ParsedUrlQuery, PreviewData>
) => {
  const category: string = context.params?.category as string;

  // fetch data
  const results = await Promise.all([
    await fetchCommonData(),
    await getMenuByName(category),
  ]);

  return {
    props: {
      ...results[0],
      category: results[1].data ?? undefined,
    },
  };
}) satisfies GetServerSideProps<{
  menus: IMenus;
  category: IMenu | undefined;
}>;

export default function Category({
  category,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <BaseLayout>
      <Head>
        <title>Dimas Wibowo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppContainer pt={24} pb={12} minH="90vh">
          {category ? <BlocksRenderer data={category?.blocks ?? []} /> : null}
        </AppContainer>
      </main>
    </BaseLayout>
  );
}
